spring.application.name=simqueue
logging.level.root=WARN;

# PostgreSQL Database Connection Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/simqueue
spring.datasource.username=postgres
spring.datasource.password=Kicking2021!

# JPA / Hibernate Configuration
# 'update' automatically creates tables in your database based on your Java Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect