package com.simqueue.simqueue.simulation;

import java.util.Random;
import java.time.LocalDateTime; // Added for timestamping if needed, or handled inside the entity

import org.springframework.stereotype.Service;

import com.simqueue.simqueue.EventService;
import com.simqueue.simqueue.simulation.model.SimulationResult;
import com.simqueue.simqueue.simulation.repository.SimulationResultRepository;

@Service
public class SimulationService {

    private final EventService eventService;
    private final SimulationResultRepository simulationResultRepository; // 1. Added Repository
    private final Random random = new Random();

    // 2. Updated constructor to include the repository
    public SimulationService(EventService eventService, SimulationResultRepository simulationResultRepository) {
        this.eventService = eventService;
        this.simulationResultRepository = simulationResultRepository;
    }

    public void runSimulation() throws InterruptedException {
        int numCustomers = 5;
        int numCashiers = 1; // Explicitly tracking this for our database record
        double totalServiceTimeSeconds = 0.0; // 3. Tracker for average calculation

        eventService.sendEvent("Simulation started with " + numCustomers + " customers.");

        for (int i = 1; i <= numCustomers; i++) {
            String name = "Customer " + i;

            // Poisson-ish arrival: exponential interarrival times (λ = 0.5 customers/sec)
            double lambda = 0.5; // arrivals per second
            double uArr = random.nextDouble();
            double interArrival = -Math.log(1 - uArr) / lambda; // exponential
            long interArrivalMs = (long) (interArrival * 1000);

            Thread.sleep(interArrivalMs);
            eventService.sendEvent(name + " arrived after " + (interArrivalMs / 1000.0) + "s.");

            // Exponential service time (μ = 0.4 customers/sec)
            double mu = 0.4;
            double uServ = random.nextDouble();
            double serviceTime = -Math.log(1 - uServ) / mu;
            
            // 4. Accumulate the true simulated service time generated by your math formula
            totalServiceTimeSeconds += serviceTime; 
            
            long serviceTimeMs = (long) (serviceTime * 1000);

            eventService.sendEvent("Cashier 1 started serving " + name +
                    " (service time ≈ " + String.format("%.2f", serviceTime) + "s).");

            Thread.sleep(500); // just pacing visuals a bit

            eventService.sendEvent("Cashier 1 finished serving " + name + ".");
        }

        // 5. Calculate the average service time from this run
        double averageServiceTimeSeconds = totalServiceTimeSeconds / numCustomers;

        // 6. Create the entity and persist it to PostgreSQL
        SimulationResult result = new SimulationResult(numCashiers, numCustomers, averageServiceTimeSeconds);
        simulationResultRepository.save(result);

        eventService.sendEvent("Simulation finished. Data successfully saved to PostgreSQL!");
    }
}